//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PayRunIORunReports.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.test.payrun.io/")]
        public string TestUrl {
            get {
                return ((string)(this["TestUrl"]));
            }
            set {
                this["TestUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9MaHMtmTUC6iMgymPl94g")]
        public string TestConsumerKey {
            get {
                return ((string)(this["TestConsumerKey"]));
            }
            set {
                this["TestConsumerKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("44sem3aVCUCxjaFmnolPQhPii7rQQwEyqgTnSJB655Q")]
        public string TestConsumerSecret {
            get {
                return ((string)(this["TestConsumerSecret"]));
            }
            set {
                this["TestConsumerSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.payrun.io/")]
        public string LiveUrl {
            get {
                return ((string)(this["LiveUrl"]));
            }
            set {
                this["LiveUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A1NQVtzi0yF7FO0KBX3PQ")]
        public string LiveConsumerKey {
            get {
                return ((string)(this["LiveConsumerKey"]));
            }
            set {
                this["LiveConsumerKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("X7QvDfQHpUGpXbDuERoUQP1qIbXuE5UuSlpIfTfVDZQ")]
        public string LiveConsumerSecret {
            get {
                return ((string)(this["LiveConsumerSecret"]));
            }
            set {
                this["LiveConsumerSecret"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("M:\\PayRunIO")]
        public string pdfReportFolder {
            get {
                return ((string)(this["pdfReportFolder"]));
            }
            set {
                this["pdfReportFolder"] = value;
            }
        }
    }
}
